version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
  auth:
    build: ./auth
    ports:
      - "3004:3004"
    restart: always
  search:
    build: ./search
    ports:
      - "3002:3002"
    links:
      - "db:database"
    restart: always
  booking:
    build: ./booking
    ports:
      - "3000:3000"
    links:
      - "db:database"
      - "auth:auth"
    restart: always
  hotel:
    build: ./hotel
    ports:
      - "3001:3001"
    links:
      - "db:database"
      - "auth:auth"
      - "search:search"
    restart: always
  ui:
    build: ./ui
    ports:
      - "3003:3003"
    links:
      - "hotel:hotel"
      - "search:search"
      - "auth:auth"
    restart: always
