version: '3.4'
services:
  booking:
    build:
      context: ../booking
    ports:
      - "3000:3000"
      - "9090:9090"
    restart: always
  room:
    build: ../room
    ports:
      - "3001:3001"
      - "9091:9091"
    restart: always
  search:
    build: ../search
    ports:
      - "3002:3002"
    restart: always
  ui:
    build: ../ui
    ports:
      - "3003:3003"
      - "9003:9003"
    restart: always
  auth:
    build: ../auth
    ports:
      - "3004:3004"
    restart: always
  report:
    build: ../report
    ports:
      - "3005:3005"
    restart: always
  utilities:
    build: ../utilities/wirebridge
    ports:
      - "8080:8080"
    restart: always
