version: '3.4'
services:
  booking:
    build: 
      context: ../booking
    ports:
      - "3000:3000"
    restart: always
  hotel:
    build: ../hotel
    ports:
      - "3001:3001"
    restart: always
  search:
    build: ../search
    ports:
      - "3002:3002"
    restart: always
  ui:
    build: ../ui
    ports:
      - "3003:3003"
      - "9003:9003"
    restart: always        
  auth:
    build: ../auth
    ports:
      - "3004:3004"
    restart: always
  report:
    build: ../report
    ports:
      - "3005:3005"
    restart: always